version: '3'

tasks:
  deploy:*:*:
    vars:
      NIXCONFIG_NAME: '{{index .MATCH 0}}'
      TARGET_HOST: '{{index .MATCH 1}}'
    cmds:
      - nixos-rebuild switch --flake .#{{.NIXCONFIG_NAME}} --target-host {{ .TARGET_HOST }} --use-remote-sudo {{.CLI_ARGS}}
  
  install:*:*:
    vars:
      NIXCONFIG_NAME: '{{index .MATCH 0}}'
      TARGET_HOST: '{{index .MATCH 1}}'
    cmd: |
      nix run github:nix-community/nixos-anywhere -- \
      --generate-hardware-config nixos-generate-config ./host/{{.NIXCONFIG_NAME}}/hardware-configuration.nix \
      --flake .#{{.NIXCONFIG_NAME}} --target-host {{.TARGET_HOST}} {{.CLI_ARGS}}

